config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
]

website/urls.py
from django.shortcuts import render
from django.urls import path
from . import views

app_name = "website"

urlpatterns = [
    path('', views.index_page_view, name='index'),
    path('carnes', views.carnes_page_view, name='carnes'),
    path('doces', views.doces_page_view, name='doces'),
    path('opiniao', views.opiniao_page_view, name='opiniao'),
    path('peixe', views.peixe_page_view, name='peixe'),
    path('veggie', views.veggie_page_view, name='veggie'),
    path('veggieReceita', views.veggieR_page_view, name='veggieReceita'),
    path('carnesReceita', views.carnesR_page_view, name='carnesReceita'),
    path('peixeReceita', views.peixeR_page_view, name='peixeReceita'),
    path('docesReceita', views.docesR_page_view, name='docesReceita'),
    path('videos', views.videos_page_view, name='videos'),
    path('quemSomos', views.quemSomos_page_view, name='quemSomos'),
    path('receitaNova', views.receitaNova_page_view, name='receitaNova'),
    path('contactos', views.contactos_page_view, name='contactos'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('quizz', views.quizz_page_view, name='quizz'),
    path('quizz_resultados/<int:id>',views.quizz_resultados,name="quizz_resultados"),
    path('edita/<int:contacto_id>', views.edita_contactos_view, name='edita'),
    path('apaga/<int:contacto_id>', views.apaga_contactos_view, name='apaga'),
    path('receitaDia', views.receitaDia_page_view, name='receitaDia'),
    path("sections/<int:num>", views.section, name="section")
]

website/models.py
from django.db import models


# Create your models here.

class contacto(models.Model):
    nome = models.CharField(max_length=20)
    apelido = models.CharField(max_length=20)
    telefone = models.IntegerField()
    email = models.EmailField(max_length=64)
    dataNasc = models.DateField()

    def __str__(self):
        return f"{self.nome} {self.apelido}"


class quizz(models.Model):
    pergunta_1 = models.CharField(max_length=2)
    pergunta_2 = models.CharField(max_length=2)
    pergunta_3 = models.CharField(max_length=2)
    pergunta_4 = models.CharField(max_length=2)
    pergunta_5 = models.CharField(max_length=15)
    pergunta_6 = models.CharField(max_length=15)
    pergunta_7 = models.CharField(max_length=15)
    pergunta_8 = models.CharField(max_length=2)
    pergunta_9 = models.CharField(max_length=2)
    pergunta_10 = models.CharField(max_length=2)

    def __str__(self):
        return f"{self.pergunta_1},{self.pergunta_2},{self.pergunta_3},{self.pergunta_4}" \
               f",{self.pergunta_5},{self.pergunta_6},{self.pergunta_7},{self.pergunta_8}" \
               f",{self.pergunta_9},{self.pergunta_10}"


class Post(models.Model):
    avaliacao = models.CharField(max_length=10)

    def __str__(self):
        return f"{self.avaliacao}"

website/forms.py
from django import forms
from django.forms import ModelForm
from .models import *


class contactoForm(ModelForm):
    class Meta:
        model = contacto
        fields = '__all__'
    # inserção de classes CSS para formatação de cada campo do formulário
        widgets = {
            'nome': forms.TextInput(attrs={'placeholder': 'Insira o seu nome'}),
            'apelido': forms.TextInput(attrs={'placeholder': 'Insira o seu apelido'}),
            'telefone': forms.TextInput(attrs={'placeholder': 'Insira o seu contacto'}),
            'email': forms.EmailInput(attrs={'placeholder': 'Ex: joda@gmail.com'}),
            'dataNasc': forms.NumberInput(attrs={'type': 'date'}),
        }

class quizzForm(ModelForm):
    class Meta:
        model = quizz
        fields = '__all__'
    # inserção de classes CSS para formatação de cada campo do formulário
        labels = {
            'pergunta_1': '1. Quantas receitas de carne exitem no nosso website?',
            'pergunta_2': '2. Quantas receitas de peixe exitem no nosso website?',
            'pergunta_3': '3. Quantas receitas de veggie exitem no nosso website?',
            'pergunta_4': '4. Quantas receitas de doces exitem no nosso website?',
            'pergunta_5': '5. Choco frito é um prato famoso de que região?',
            'pergunta_6': '6. Em 2020 q restaurante recebeu uma estrela Michelin?',
            'pergunta_7': '7. As migas é um prato famoso de que região?',
            'pergunta_8': '8. Quantas estrelas michelins têm o Chef Pedro Lemos?',
            'pergunta_9': '9. Quantas estrelas michelins têm o Chef José Avillez?',
            'pergunta_10': '10. Quantas estrelas michelins têm o Chef Ricardo.C?',
        }

website/views.py
import random

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.shortcuts import render
from django.urls import reverse
from matplotlib import pyplot as plt

from website.forms import *
from .models import *


def index_page_view(request):
    return render(request, 'website/index.html')


def carnes_page_view(request):
    return render(request, 'website/carnes.html')


def doces_page_view(request):
    return render(request, 'website/doces.html')

def funcao_post():
    post_get = Post.objects.all()
    avaliacoes = [0, 0, 0, 0, 0]

    for i in post_get:
        if i.avaliacao == "1":
            avaliacoes[0] += 1
        elif i.avaliacao == "2":
            avaliacoes[1] += 1
        elif i.avaliacao == "3":
            avaliacoes[2] += 1
        elif i.avaliacao == "4":
            avaliacoes[3] += 1
        elif i.avaliacao == "5":
            avaliacoes[4] += 1

    plt.title("Avaliações do Website")
    plt.bar([1, 2, 3, 4, 5], avaliacoes)
    plt.xlabel('★ Rating ★')
    plt.ylabel('N º Avaliações')
    plt.savefig('website/static/website/images/quizz2.png')



def opiniao_page_view(request):

    funcao_post()
    context = {
        'imagem2': plt
    }
    plt.close()


    if request.method == 'POST':
        if request.POST.get('avaliacao', "0"):
            post = Post()
            post.avaliacao = request.POST.get('avaliacao', "0")
            post.save()
            funcao_post()
            context = {
                'imagem2': plt
            }
            plt.close()

            return render(request, 'website/opiniao.html', context=context)
    else:
        return render(request, 'website/opiniao.html', context=context)


def peixe_page_view(request):
    return render(request, 'website/peixe.html')


def veggie_page_view(request):
    return render(request, 'website/veggie.html')


def veggieR_page_view(request):
    return render(request, 'website/veggieReceita.html')


def carnesR_page_view(request):
    return render(request, 'website/carneReceita.html')


def peixeR_page_view(request):
    return render(request, 'website/peixeReceita.html')


def docesR_page_view(request):
    return render(request, 'website/doceReceita.html')


def videos_page_view(request):
    return render(request, 'website/videos.html')


def quemSomos_page_view(request):
    return render(request, 'website/quemSomos.html')


def receitaNova_page_view(request):
    return render(request, 'website/receitaNova.html')


def quizz_page_view(request):
    form = quizzForm(request.POST or None)
    if form.is_valid():
        form_fields = form.save()
        return HttpResponseRedirect('quizz_resultados/' + str(form_fields.id))

    context = {'form': form}

    return render(request, 'website/quizz.html', context=context)


def quizz_resultados(request, id):
    quizz_get = quizz.objects.get(pk=id)
    cotacao = 0
    certos = []

    if (quizz_get.pergunta_1 == '12'):
        cotacao += 10
        certos.append(1)
    else:
        certos.append(0)

    if (quizz_get.pergunta_2 == '12'):
        cotacao += 10
        certos.append(1)
    else:
        certos.append(0)

    if (quizz_get.pergunta_3 == '12'):
        cotacao += 10
        certos.append(1)
    else:
        certos.append(0)

    if (quizz_get.pergunta_4 == '18'):
        cotacao += 10
        certos.append(1)
    else:
        certos.append(0)

    if (quizz_get.pergunta_5.lower() == 'setubal'):
        cotacao += 10
        certos.append(1)
    else:
        certos.append(0)

    if (quizz_get.pergunta_6.lower() == '100 maneiras'):
        cotacao += 10
        certos.append(1)
    else:
        certos.append(0)

    if (quizz_get.pergunta_7.lower() == 'alentejo'):
        cotacao += 10
        certos.append(1)
    else:
        certos.append(0)

    if (quizz_get.pergunta_8 == '1'):
        cotacao += 10
        certos.append(1)
    else:
        certos.append(0)

    if (quizz_get.pergunta_9 == '1'):
        cotacao += 10
        certos.append(1)
    else:
        certos.append(0)

    if (quizz_get.pergunta_10 == '2'):
        cotacao += 10
        certos.append(1)
    else:
        certos.append(0)

    labels = ['Certos', 'Errados']
    sizes = [cotacao, 100 - cotacao]
    fig1, ax1 = plt.subplots()
    colors = ['#F8D167', '#987456']
    explode = (0.01, 0.01)
    ax1.pie(sizes, autopct='%1.1f%%', startangle=90, colors=colors, pctdistance=0.80, explode=explode)
    centre_circle = plt.Circle((0, 0), 0.60, fc='white')
    sumstr = str(int(cotacao / 10)) + "/10"
    ax1.text(0., 0., sumstr, horizontalalignment='center', verticalalignment='center', fontsize=30)
    fig = plt.gcf()
    fig.gca().add_artist(centre_circle)
    ax1.axis('equal')
    plt.legend(title="Resultados:", labels=labels)
    plt.tight_layout()
    plt.savefig('website/static/website/images/quizz.png')

    context = {
        'quizz': quizz_get,
        'resultado': cotacao,
        'imagem': plt
    }

    return render(request, 'website/quizz_resultado.html', context)


def contactos_page_view(request):
    form = contactoForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('website:contactos'))

    context = {'form': form, 'contactos': contacto.objects.all()}

    return render(request, 'website/contactos.html', context)


def edita_contactos_view(request, contacto_id):
    contactoEditar = contacto.objects.get(pk=contacto_id)
    form = contactoForm(request.POST or None, instance=contactoEditar)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('website:contactos'))

    context = {'form': form, 'contacto_id': contacto_id}
    return render(request, 'website/edita.html', context)


def apaga_contactos_view(request, contacto_id):
    contacto.objects.get(id=contacto_id).delete()
    return HttpResponseRedirect(reverse('website:contactos'))


def login_view(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(
            request,
            username=username,
            password=password
        )

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('website:index'))
        else:
            return render(request, 'website/login.html', {
                'message': 'Credenciais inválidas.'
            })

    return render(request, 'website/login.html')


def logout_view(request):
    logout(request)
    return render(request, 'website/index.html', {
        'message': 'Insira os Seus Dados'})

def receitaDia_page_view(request):
    return render(request, 'website/ReceitaDoDia.html')

texts = ["website/carnesDia.html","website/doceDia.html","website/peixeDia.html"]

def section(request, num):
    if num == 1:
        return HttpResponse(render(request, random.choice(texts)))
    else:
        raise Http404("No such section")

website/templates/website/base.html
<!DOCTYPE html>
{% load static %}
<html lang="pt">

<head>
  <meta charset="UTF-8">
  <meta name="author" content="ANONIMUS">
  <meta name="keywords" content="Culinaria">
  <meta name="description" content="Culinaria á portuguesa">
  {% load static %}
  <link rel="shortcut icon" type="image/x-icon" href="{% static "website/images/icon.png" %}"/>
  <link href="{% static "website/css/estilos.css" %}" type="text/css" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link type="text/css" rel="stylesheet" href="path-to-fontawesome/font-awesome.css">
  <title>CulinariaJoDa - Receitas portuguesas</title>
</head>

<body>
  <br>
  <div class="parent">
    <div class="div1">
      <header>
        <center>
          <figure>
            <img class="resize" src="{% static "website/images/logo2.png" %}" alt="Culinaria JoDa">
          </figure>
        </center>
      </header>
    </div>

    <div class="div2">
      <nav>
        <center>
          <p>
          <div class="dropdown">
            <b><a class="dropbtn" href="{% url 'website:index' %}" {% if request.resolver_match.url_name == 'index' or request.resolver_match.url_name == 'carnes' or request.resolver_match.url_name == 'peixe' or request.resolver_match.url_name == 'doces' %}style="border-bottom: 5px solid rgb(248, 209, 103)"{% endif %}>RECEITAS <i
                  class="fa fa-chevron-down" style="font-size: 13px;"></i></a></b>
            <div class="dropdown-content">
              <a href="{% url 'website:carnes' %}" {% if request.resolver_match.url_name == 'carnes' %}style="border-bottom: 5px solid rgb(248, 209, 103)"{% endif %}>Pratos de Carne</a>
              <a href="{% url 'website:peixe' %}" {% if request.resolver_match.url_name == 'peixe' %}style="border-bottom: 5px solid rgb(248, 209, 103)"{% endif %}>Pratos de peixe</a>
              <a href="{% url 'website:doces' %}" {% if request.resolver_match.url_name == 'doces' %}style="border-bottom: 5px solid rgb(248, 209, 103)"{% endif %}>Doces e sobremesas</a>
            <a href="{% url 'website:receitaDia' %}" {% if request.resolver_match.url_name == 'receitaDia' %}style="border-bottom: 5px solid rgb(248, 209, 103)"{% endif %}>Receita do Dia</a>
            </div>
          </div>
          <b>
            <a href="{% url 'website:videos' %}" {% if request.resolver_match.url_name == 'videos' %}style="border-bottom: 5px solid rgb(248, 209, 103)"{% endif %}>VIDEOS</a>
            <a href="{% url 'website:veggie' %}" {% if request.resolver_match.url_name == 'veggie' %}style="border-bottom: 5px solid rgb(248, 209, 103)"{% endif %}>VEGGIE</a>
            <a href="{% url 'website:quemSomos' %}" {% if request.resolver_match.url_name == 'quemSomos' %}style="border-bottom: 5px solid rgb(248, 209, 103)"{% endif %}>QUEM SOMOS</a>
            <a href="{% url 'website:quizz' %}" {% if request.resolver_match.url_name == 'quizz' %}style="border-bottom: 5px solid rgb(248, 209, 103)"{% endif %}>QUIZ</a>
          </b>
          <div class="dropdown">
            <b><a class="dropbtn" href="#home" {% if request.resolver_match.url_name == 'receitaNova' or request.resolver_match.url_name == 'opiniao' or request.resolver_match.url_name == 'contactos' %}style="border-bottom: 5px solid rgb(248, 209, 103)"{% endif %}>COMUNIDADE <i class="fa fa-chevron-down"
                  style="font-size: 13px;"></i></a></b>
            <div class="dropdown-content">
              <a href="{% url 'website:receitaNova' %}" {% if request.resolver_match.url_name == 'receitaNova' %}style="border-bottom: 5px solid rgb(248, 209, 103)"{% endif %}>A sua Receita</a>
              <a href="{% url 'website:opiniao' %}" {% if request.resolver_match.url_name == 'opiniao' %}style="border-bottom: 5px solid rgb(248, 209, 103)"{% endif %}>Deixe-nos a sua Opinião</a>
              <a href="{% url 'website:contactos' %}" {% if request.resolver_match.url_name == 'contactos' %}style="border-bottom: 5px solid rgb(248, 209, 103)"{% endif %}>O Seu Contacto</a>
            </div>
          </div>
            </p>
        </center>
      </nav>
    </div>

    <div class="div3">
      <main>
          {% block main %}
          {% endblock main %}
      </main>
    </div>

    <div class="div4">
      <aside>
        <section style="border: 3px solid black;padding: 40px">
            {% if request.user.username %}
                <h4 style="text-align: center;"><span
              style="text-align: center;">Bem Vindo, Chefe {{ request.user.first_name }}!</span></h4>
                <a href="{% url 'website:logout' %}" style = "margin-bottom: 60px"><button type="button" >LOGOUT</button></a>
                 {% else %}
                <h4 style="text-align: center;"><span
              style="text-align: center;">Torne-se Num Chefe!</span></h4>
                <a href="{% url 'website:login' %}"><button type="button" >LOGIN</button></a>
            {% endif %}
        </section>
      {% if request.resolver_match.url_name != 'quemSomos' %}
        <section>
          <h4 class="block-title" style="text-align: center;"><span
              style="background-color: rgb(248, 209, 103); padding: 3px;">Videos Populares</span></h4>
          <iframe width="300" height="200" src="https://www.youtube.com/embed/cwUajKqP-bs" title="YouTube video player"
            frameborder="0" allow="accelerometer;
           autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          <p style="text-align:left; margin-top: 2px;">&#128104&#8205&#127859 Caldeirada Portuguesa</p>
        </section>
        <hr>
        <br>
        <section>
          <iframe width="300" height="200" src="https://www.youtube.com/embed/qULdIKFhG9Q" title="YouTube video player"
            frameborder="0" allow="accelerometer; autoplay;
           clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          <p style="text-align:left; margin-top: 2px;">&#128104&#8205&#127859 Arroz de Pato</p>
        </section>
      {% else %}
        <section>
          <h4 class="block-title" style="text-align: center;margin-top: 30px;">
            <span style="background-color: rgb(248, 209, 103); padding: 3px;">Fonte das Imagens</span></h4>
          <a href="https://www.saborintenso.com/"><img width="200" height="250" src="{% static "website/images/sabor.jpg" %}" alt="sabor"></a>
          <br>
        </section>
        <br>
        <h4 class="block-title" style="text-align: center;"><span style="background-color: rgb(248, 209, 103); padding: 3px;">Wordcloud</span></h4>
        <svg width="300" height="225">
          <image href="{% static "website/images/wordcloud.jpg" %}"></image>
          <a href="{% url 'website:veggie' %}">
            <polygon opacity="0" points="120,29 120,50 183,50 183,29"></polygon>
          </a>
          <a href="{% url 'website:index' %}">
            <polygon opacity="0" points="69,63 69,90 236,90 236,63"></polygon>
          </a>
          <a href="{% url 'website:doces' %}">
            <polygon opacity="0" points="197,98 197,110 247,110 247,98"></polygon>
          </a>
          <a href="{% url 'website:carnes' %}">
            <polygon opacity="0" points="86,113 86,136 214,136 214,113"></polygon>
          </a>
          <a href="{% url 'website:peixe' %}">
            <polygon opacity="0" points="91,143 91,176 210,176 210,143"></polygon>
          </a>
        </svg>
      {% endif %}
      </aside>

      <aside>
        <section>
          <br>
          <h4 class="block-title" style="text-align: center;"><span
              style="background-color: rgb(248, 209, 103); padding: 3px;">Livros Culinaria</span></h4>
          <div style="position: relative; left: 0; top: 0;">
            <img class="imgBottom" width="150" height="200" src="{% static "website/images/frase1.jpg" %}" alt="frase1">
            <img class="imgTop" width="150" height="200" src="{% static "website/images/livroVegan.png" %}" alt="frase1">
          </div>
          <br>
        </section>
      </aside>
    </div>
  </div>
  <br>
  <div class="div5">
  <footer>
    <center>
      <div class="row">
        <div class="column">
          <p><img src="{% static "website/images/logoFot.png" %}" alt="Culinaria JoDa" width="120" height="100"></p>
        </div>
        <div class="column">
          <b>
            <p>Sobre Nós:
          </b>
          <br><br>
          Se procura receitas deliciosas e práticas, quer inspirar-se e partilhar
          ideias úteis para renovar as refeições do seu dia-a-dia, seja bem-vindo, está na página certa!</p>
        </div>
        <div class="column">
          <b>
            <p>Siga-Nos:
          </b>
          <br><br><br>
          <a href="https://www.facebook.com/ReceitaseDicasCulinaria/" target="_blank" class="fa fa-lg fa-facebook"></a>
          |
          <a href="https://www.instagram.com/receitasportuguesas/?hl=pt" target="_blank"
            class="fa fa-lg fa-instagram"></a> |
          <a href="https://twitter.com/receitasdept" target="_blank" class="fa fa-lg fa-twitter"></a> |
          <a href="{% static "website/images/idk.jpg" %}" target="_blank" class="fa fa-lg fa-github"></a></p>
        </div>
      </div>
    </center>
  </footer>
</div>
</body>

</html>

website/templates/website/login.html
{% extends "website/base.html" %}

{% block main %}
    <h2 style="text-align: left;margin-left: 10px; border-bottom: 5px solid rgb(248, 209, 103);">TORNE-SE NUM CHEFE!</h2>
    {% if message %}
        <div> {{ message }} </div>
    {% endif %}
    <form action="{% url 'website:login' %}" method="POST">
        {% csrf_token %}
        <fieldset  style="text-align: center;padding: 20px">
          <legend><b>LOGIN</b></legend>
            <input type="text" name="username" placeholder="username"><br>
            <input type="password" name="password" placeholder="password"><br><br>
            <input type="submit" value="Login">
        </fieldset>
    </form>

{% endblock %}

website/templates/website/quizz.html
{% extends "website/base.html" %}

{% block main %}
    <section>
    <h2 style="text-align: left;margin-left: 10px; border-bottom: 5px solid rgb(248, 209, 103);">QUIZ CULINARIA</h2>
      <form action="" method="POST">
        <fieldset  style="text-align: left;">
          <legend><b>Perguntas:</b></legend>
              {% csrf_token %}
              {{ form.as_p }}
        <input type="submit" value="Gravar" class="btn btn-success" >
        </fieldset>
       </form>
    </section>
{% endblock %}

website/templates/website/receitaNova.html
{% extends "website/base.html" %}

{% block main %}
    <section>
      <h2 style="text-align: left;margin-left: 10px; border-bottom: 5px solid rgb(248, 209, 103);">DEIXE AQUI A SUA RECEITA</h2>
      <form action="mailto:jodaculinaria@gmail.com" method="post">
        <fieldset  style="text-align: left;">
          <legend><b>Identificação:</b></legend>
          <div class="row">
            <div class="column">
              <p>Nome: <br> <input class="comentar" type="text" id="nome" name="nome" size="20" maxlength="20" placeholder="Insira nome"
                  autofocus required></p>
              <p>Apelido: <br> <input class="comentar" type="text" id="apelido" name="apelido" size="20" maxlength="20"
                  placeholder="Insira apelido" required></p>
              <p>Email: <br> <input class="comentar" type="email" id="email" name="email" autocomplete="on" placeholder="Insira email"
                  required></p>
            </div>
            <div class="column">
                {% load static %}
              <img src="{% static "website/images/receita.png" %}" alt="Culinaria JoDa" width="250" height="150" style="text-align: center;margin-top: 40px;margin-left: 70px;">
            </div>
          </div>
          <label for="file-upload" class="custom-file-upload">
            <i class="fa fa-cloud-upload"></i> Fotos da Receita
          </label>
          <input id="file-upload" type="file" name="filename"/>
          <br><br>
            <textarea class="comentar"  style="resize: vertical;
            overflow: auto;" name="mensagem" rows="10" cols="60%" placeholder="Insira aqui a sua Receita"  autofocus required></textarea>
          <br><br>
          <input type="submit" value="Submit">
          <input type="reset" value="Reset">
        </fieldset>
      </form>
      <br>
    </section>
    <h4 class="block-title"><span style="background-color: rgb(248, 209, 103); padding: 3px;">Receitas Publicadas Recentemente</span></h4>
    <section >
      <div class="flex-container">
          <a href="{% url 'website:peixe' %}"><img class="color" src="{% static "website/images/Massa-com-Atum.jpg" %}" alt="Massa-com-Atum"></a>
          <a href="{% url 'website:carnes' %}"><img class="color" src="{% static "website/images/Coxinhas-de-Frango.jpg" %}" alt="Coxinhas-de-Frango"></a>

          <a href="{% url 'website:peixe' %}"><img class="color" src="{% static "website/images/Petisco-de-Sardinhas.jpg" %}"  alt="Petisco-de-Sardinhas"></a>
          <a href="{% url 'website:carnes' %}"><img class="color" src="{% static "website/images/Massa-Gratinada-Frango.jpg" %}" alt="Mousse-de-Iogurte-Grego-e-Morango"></a>

          <a href="{% url 'website:doces' %}"><img class="color" src="{% static "website/images/Bolas-de-Berlim.jpg" %}"  alt="Bolas-de-Berlim"> </a>
          <a href="{% url 'website:veggie' %}"><img class="color" src="{% static "website/images/Crepes-de-Legumes.jpg" %}" alt="Crepes-de-Legumes"></a>
      </div>
    </section>
  </section>
{% endblock %}